export enum NoteClass {
  article = 'Article',
  author = 'Author',
  book = 'Book',
  bookSeries = 'BookSeries',
  character = 'Character',
  dailyNote = 'DailyNote',
  dialog = 'Dialog',
  meeting = 'Meeting',
  movie = 'Movie',
  note = 'Note',
  place = 'Place',
  show = 'Show',
  task = 'Task',
  term = 'Term',
  videoGame = 'VideoGame',
  videoGameSeries = 'VideoGameSeries',
  view = 'View',
  youTubeChannel = 'YouTubeChannel',
  youTubeVideo = 'YouTubeVideo'
}
