export enum RawGoodreadsType {
  award = 'Award',
  book = 'Book',
  bookDetails = 'BookDetails',
  bookGenre = 'BookGenre',
  bookSeries = 'BookSeries',
  bookContributorEdge = 'BookContributorEdge',
  bookOrWorkStats = 'BookOrWorkStats',
  booksConnection = 'BooksConnection',
  character = 'Character',
  contributor = 'Contributor',
  contributorFollowersConnection = 'ContributorFollowersConnection',
  contributorWorksConnection = 'ContributorWorksConnection',
  genre = 'Genre',
  resourceQuotesConnection = 'ResourceQuotesConnection',
  review = 'Review',
  series = 'Series',
  shelf = 'Shelf',
  shelving = 'Shelving',
  user = 'User',
  work = 'Work',
  workDetails = 'WorkDetails'
}
